# Generated by Django 2.1.3 on 2018-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.ManyToManyField(to='people.Person')),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='person',
            new_name='people',
        ),
    ]
