# Generated by Django 2.1.3 on 2018-11-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='people',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
