# Generated by Django 2.1.3 on 2018-11-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_group_people'),
        ('people', '0005_auto_20181119_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(to='group.Group'),
        ),
    ]
