# Generated by Django 2.1.3 on 2018-11-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20181124_1830'),
        ('people', '0009_auto_20181124_2010'),
    ]

    operations = [
    ]
