# Generated by Django 2.1.3 on 2018-11-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_merge_20181124_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Invalid email!'}, max_length=254),
        ),
    ]
