# Generated by Django 2.1.3 on 2018-11-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20181124_2132'),
        ('people', '0011_auto_20181124_2217'),
    ]

    operations = [
    ]
