# Generated by Django 2.1.3 on 2018-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_merge_20181124_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
